### ISSUE TITLE
v3.3.0-RC3 not published?

### ISSUE THREAD

**Issue by durban** [zio/interop-cats#517]
There is a version `3.3.0-RC3` on GitHub, but I can't seem to find it on Maven Central: https://search.maven.org/artifact/dev.zio/zio-interop-cats_2.13.

**Comment by nightscape** [comment]
Same for `3.2.9.2` which contains fixes required for Cats 3.3

**Comment by nightscape** [comment]
@adamgfraser I think I found the problem with `3.2.9.2`:
The corresponding commit has two tags, `3.2.9.1` and `3.2.9.2`.
The sbt-git plugin decides to use the `3.2.9.1` version and the upload to Sonatype fails because that version was already uploaded.
This behaviour isn't great (I think it should choose the latest version), but it should be easy to work around it by making some small change and commit and tag the new version on that commit.
