### ISSUE TITLE
Suspect publish of `23.0.0.3`

### ISSUE THREAD

**Issue by davesmith00000** [zio/interop-cats#658]
Hi - just wanted to flag this as I can't tell if it's an error or not:

Officially the version is `23.0.0.3`
For Scala.js at least, it resolves as `23.0.03` (perhaps someone accidentally forget the dot?)
Scaladex lists it as `23.0.3` (presumably because `03 == 3` :grimacing:)

On the other hand I could just be confused, the versioning system is quite full on. :smile:

**Comment by rbbowd** [comment]
There is evidence that they did make a release of `23.0.03`, see https://index.scala-lang.org/zio/interop-cats/artifacts/zio-interop-cats/23.0.3 and https://github.com/zio/zio-json/pull/919.

I suggest bumping the current version to `23.1.0.0` otherwise scala-steward will continue to make PRs suggesting that projects should upgrade to the `23.0.03` phantom release.

**Comment by jsoref** [comment]
@neko-kai @adamgfraser can you please seriously consider properly bumping to `23.1.0.0`? 

Thank you for your attention.

**Comment by neko-kai** [comment]
@jsoref @rbbowd @davesmith00000 `23.1.0.0` is released.
