### ISSUE TITLE
Separate interop with cats-core

### ISSUE THREAD

**Issue by laurynasl-wix** [zio/interop-cats#94]
Hi,

I think it would it make sense to have a separate package for interop only with cats-core (excluding cats-effect). That way if I am only using cats-core for functional goodness, I wouldn't need to bring in cats-effect as a transitive dependency into my build. 

Thoughts?

**Comment by ghostdogpr** [comment]
Actually the cats-effect library is marked as `Optional` in sbt, which means you won't get it unless you explicitly add it (or have it from another library) => https://github.com/zio/interop-cats/blob/master/build.sbt

**Comment by ghostdogpr** [comment]
Ah, but [this file](https://github.com/zio/interop-cats/blob/master/interop-cats/shared/src/main/scala/zio/interop/cats.scala) is mixing both so if you only need e.g. `Monad` it might require everything

@neko-kai what do you think?

**Comment by neko-kai** [comment]
@laurynasi-wix @ghostdogpr 
I guess it shouldn't be Optional because you'll get linking failures trying to use implicits from the catz object without CE on the classpath.
But, the way it's structured right now it's possible to add a `object core extends CatsInstances2` and if you import that object instead it will work. @laurynasi-wix Could you try to make that object and see if it works for you?

tbh, ideally I'd like to get rid of the catz object completely and put the instances into ZIO companion, using [one](https://github.com/zio/zio/issues/815) or [another] (https://github.com/typelevel/cats/pull/3043#issuecomment-529497341) version of Optional instances trick. The second one would be ideal, but I couldn't get it to work with Scala 2 without abusing sbt's evictions - unlike Dotty, Scala 2 does not tolerate undefined types in generic parameter of superclass during implicit search.

**Comment by neko-kai** [comment]
@ghostdogpr opened https://github.com/zio/interop-cats/pull/95/files

**Comment by laurynasl-wix** [comment]
Nice, thank you very much!
